name: ion_it
description: iON-it app.

publish_to: "none"

version: 4.5.8+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.21.0+1
  flutter_sms: ^2.3.2
  google_maps_flutter: ^2.0.3
  dio: ^4.0.0
  provider: ^5.0.0
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  geocoding: ^2.0.0
  simple_html_css: ^3.0.1
  shared_preferences: ^2.0.5
  flutter_polyline_points: ^1.0.0
  location: ^4.3.0
  flutter_launcher_icons: ^0.9.0
  page_transition: ^2.0.4
  rename: ^1.3.1
  app_settings:
  firebase_messaging: ^10.0.8
  flutter_local_notifications:
  firebase_core:

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Arial
      fonts:
        - asset: fonts/Arial.ttf
  assets:
    - assets/svg/
    - assets/images/

  uses-material-design: true
